


# Permalinks
permalink:        pretty

# Setup
title:            HC-MID astronomy manuscript projects
tagline:          'Latin astronomical texts'
description:      'Planning for MID projects on Latin translations of Aratus, Phaenomena.'


baseurl: '/astronomy/'


author:
  name:           'Neel Smith'


links:
  - title: Home page
    url:  /
  - title: Github repo
    url:  https://github.com/hcmid/astronomy
    external: true
  - title: HC MID club
    url: http://hcmid.github.io/
    external: true
